(()=>{
  if(window.__afjrotcTaskWorkspace)return;
  window.__afjrotcTaskWorkspace=true;
  const sb=window.adminSupabase;if(!sb)return;
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let tasks=[],profiles=[],selectedId=null,listTab='all',detailTab='overview',currentUser=null,currentProfile=null;
  const roleLabel=r=>r==='command_staff'?'Command Staff':r==='class_leader'?'Class Leaders':r==='instructor'?'Instructors':r==='cadet'?'Cadets':'';
  const statusLabel=s=>s==='in_progress'?'In Progress':s==='completed'?'Completed':'Not Started';
  const priorityLabel=p=>p==='urgent'?'Urgent':p==='high'?'High Priority':p==='low'?'Low':'Normal';
  const localDateKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
  const todayKey=()=>localDateKey(new Date());
  const addDays=(key,n)=>{const d=new Date(key+'T00:00:00');d.setDate(d.getDate()+n);return localDateKey(d)};
  const fmtDate=(key,opts={month:'short',day:'numeric'})=>key?new Date(key+'T00:00:00').toLocaleDateString('en-US',opts):'—';
  const fmtTime=v=>v?new Date(v).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'';
  const isDone=t=>t.completed||t.status==='completed';
  const isOverdue=t=>!isDone(t)&&t.due_date&&t.due_date<todayKey();
  const isDueSoon=t=>!isDone(t)&&t.due_date&&t.due_date>=todayKey()&&t.due_date<=addDays(todayKey(),7);
  const personName=id=>profiles.find(p=>p.id===id)?.full_name||'';
  const assignment=t=>[t.assigned_to?personName(t.assigned_to):'',t.assigned_role?roleLabel(t.assigned_role):''].filter(Boolean).join(' / ')||'Unassigned';

  function loadCss(){if(document.getElementById('adminTasksCss'))return;const l=document.createElement('link');l.id='adminTasksCss';l.rel='stylesheet';l.href='/admin-tasks.css?v=1';document.head.appendChild(l)}
  function ensureNav(){const nav=document.querySelector('.admin-nav');if(!nav)return;if(!nav.querySelector('[data-section="tasks"]')){const b=document.createElement('button');b.type='button';b.dataset.section='tasks';b.innerHTML='<span class="task-nav-icon">☑</span><span>Tasks</span>';const content=nav.querySelector('[data-section="content"]');content?.insertAdjacentElement('afterend',b)||nav.appendChild(b)}if(!nav.querySelector('[data-task-site-management]')){const b=document.createElement('button');b.type='button';b.dataset.taskSiteManagement='1';b.innerHTML='<span class="task-nav-icon">⚙</span><span>Site Management</span>';nav.appendChild(b)}}
  function ensureWorkspace(){if($('taskWorkspace'))return;const main=document.querySelector('.admin-main');if(!main)return;main.insertAdjacentHTML('beforeend',`<section id="taskWorkspace" class="task-workspace hidden"><header class="task-head"><div><h1>Task Management</h1><p>Plan, assign, track, and complete unit tasks.</p></div><div class="task-tools"><input id="taskSearch" type="search" placeholder="Search tasks…"><select id="taskStatusFilter"><option value="">All statuses</option><option value="not_started">Not Started</option><option value="in_progress">In Progress</option><option value="overdue">Overdue</option><option value="completed">Completed</option></select><button id="createTaskBtn" class="task-create-btn" type="button">＋ Create Task</button></div></header><section class="task-summary"><article class="task-summary-card open"><div><small>Open Tasks</small><b id="taskOpenCount">0</b></div><span class="task-summary-icon">▣</span></article><article class="task-summary-card soon"><div><small>Due Soon</small><b id="taskDueSoonCount">0</b></div><span class="task-summary-icon">◷</span></article><article class="task-summary-card overdue"><div><small>Overdue</small><b id="taskOverdueCount">0</b></div><span class="task-summary-icon">!</span></article><article class="task-summary-card done"><div><small>Completed</small><b id="taskCompletedCount">0</b></div><span class="task-summary-icon">✓</span></article></section><div class="task-layout"><section class="task-list-panel"><nav class="task-list-tabs"><button class="active" data-task-list-tab="all">All Tasks</button><button data-task-list-tab="mine">My Tasks</button><button data-task-list-tab="assigned">Assigned Tasks</button><button data-task-list-tab="completed">Completed</button></nav><div class="task-table-wrap"><table class="task-table"><thead><tr><th>Task</th><th>Category</th><th>Priority</th><th>Due Date</th><th>Assigned To</th><th>Status</th></tr></thead><tbody id="taskTableBody"></tbody></table></div><div id="taskListCount" class="task-list-count"></div></section><aside id="taskDetail" class="task-detail"><div class="task-empty">Select a task to view its details.</div></aside></div></section>`)}
  function ensureModal(){if($('taskModal'))return;document.body.insertAdjacentHTML('beforeend',`<div id="taskModal" class="task-modal hidden"><div class="task-modal-card"><div class="task-modal-head"><h2 id="taskModalTitle">Create Task</h2><button type="button" data-close-task-modal>×</button></div><form id="taskForm" class="task-form"><input id="taskFormId" type="hidden"><label class="full">Task Title<input id="taskFormTitle" required maxlength="180"></label><label class="full">Description<textarea id="taskFormDescription" maxlength="1600" placeholder="What needs to be done?"></textarea></label><label>Category<select id="taskFormCategory"><option>Inspection</option><option>Uniforms</option><option>Community Service</option><option>Events</option><option>Training</option><option>Content</option><option>Administration</option><option>Other</option></select></label><label>Priority<select id="taskFormPriority"><option value="low">Low</option><option value="normal" selected>Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></label><label>Due Date<input id="taskFormDueDate" type="date"></label><label>Status<select id="taskFormStatus"><option value="not_started">Not Started</option><option value="in_progress">In Progress</option><option value="completed">Completed</option></select></label><label>Assign to Person<select id="taskFormPerson"><option value="">No specific person</option></select></label><label>Assign to Role<select id="taskFormRole"><option value="">No role group</option><option value="command_staff">Command Staff</option><option value="class_leader">Class Leaders</option><option value="instructor">Instructors</option><option value="cadet">Cadets</option></select></label><label class="full">Internal Notes<textarea id="taskFormNotes" maxlength="2000" placeholder="Private admin notes about this task"></textarea></label><div id="taskFormStatusText" class="task-form-status"></div><div class="task-form-actions"><button id="deleteTaskBtn" class="danger hidden" type="button">Delete Task</button><div class="task-form-actions-right"><button type="button" data-close-task-modal>Cancel</button><button class="primary" type="submit">Save Task</button></div></div></form></div></div>`)}
  function ensureUI(){loadCss();ensureNav();ensureWorkspace();ensureModal()}
  function setActiveNav(key){document.querySelectorAll('.admin-nav button').forEach(b=>b.classList.toggle('active',b.dataset.section===key))}
  function hideTasks(){$('taskWorkspace')?.classList.add('hidden')}
  function hideOther(){document.querySelectorAll('.command-head,.stats-grid,.dashboard-grid,.bottom-grid,#cadetWorkspace,#contentWorkspace').forEach(x=>x.classList.add('hidden'));$('taskWorkspace')?.classList.remove('hidden');setActiveNav('tasks')}
  async function showTasks(){ensureUI();hideOther();await loadTasks()}

  async function safe(p,f=[]){try{const {data,error}=await p;if(error)throw error;return data??f}catch(e){console.warn('Task workspace query failed',e);return f}}
  async function loadTasks(){
    ensureUI();
    const [taskRows,people,userResult]=await Promise.all([
      safe(sb.from('command_todos').select('*').order('completed',{ascending:true}).order('due_date',{ascending:true,nullsFirst:false}).order('created_at',{ascending:false})),
      safe(sb.from('profiles').select('id,full_name,role').order('full_name')),
      sb.auth.getUser()
    ]);
    tasks=taskRows;profiles=people;currentUser=userResult?.data?.user||null;currentProfile=profiles.find(p=>p.id===currentUser?.id)||null;
    populatePeople();
    if(selectedId&&!tasks.some(t=>t.id===selectedId))selectedId=null;
    if(!selectedId&&tasks.length)selectedId=(tasks.find(t=>!isDone(t))||tasks[0]).id;
    renderSummary();renderList();renderDetail();syncCommandCenterStat();
  }
  function populatePeople(){const s=$('taskFormPerson');if(!s)return;const current=s.value;s.innerHTML='<option value="">No specific person</option>'+profiles.map(p=>`<option value="${p.id}">${esc(p.full_name||'Unnamed')} · ${esc(roleLabel(p.role)||p.role)}</option>`).join('');if(profiles.some(p=>p.id===current))s.value=current}
  function renderSummary(){const open=tasks.filter(t=>!isDone(t)),soon=open.filter(isDueSoon),over=open.filter(isOverdue),done=tasks.filter(isDone);$('taskOpenCount').textContent=open.length;$('taskDueSoonCount').textContent=soon.length;$('taskOverdueCount').textContent=over.length;$('taskCompletedCount').textContent=done.length}
  function syncCommandCenterStat(){const open=tasks.filter(t=>!isDone(t)),over=open.filter(isOverdue),soon=open.filter(isDueSoon);if($('statTasks'))$('statTasks').textContent=open.length;if($('statTaskNote'))$('statTaskNote').textContent=over.length?`${over.length} overdue`:soon.length?`${soon.length} due soon`:open.length?'In progress':'All clear'}
  function filteredTasks(){let rows=[...tasks];if(listTab==='mine')rows=rows.filter(t=>t.assigned_to===currentUser?.id||(t.assigned_role&&t.assigned_role===currentProfile?.role));else if(listTab==='assigned')rows=rows.filter(t=>!!t.assigned_to||!!t.assigned_role);else if(listTab==='completed')rows=rows.filter(isDone);const status=$('taskStatusFilter')?.value||'';if(status==='overdue')rows=rows.filter(isOverdue);else if(status)rows=rows.filter(t=>(isDone(t)?'completed':t.status||'not_started')===status);const q=($('taskSearch')?.value||'').trim().toLowerCase();if(q)rows=rows.filter(t=>`${t.title||''} ${t.notes||''} ${t.category||''} ${assignment(t)} ${statusLabel(t.status)}`.toLowerCase().includes(q));return rows}
  function dateClass(t){return isDone(t)?'completed':isOverdue(t)?'overdue':isDueSoon(t)?'soon':''}
  function renderList(){document.querySelectorAll('[data-task-list-tab]').forEach(b=>b.classList.toggle('active',b.dataset.taskListTab===listTab));const rows=filteredTasks(),body=$('taskTableBody');if(!body)return;body.innerHTML=rows.map(t=>`<tr data-task-id="${t.id}" class="${t.id===selectedId?'selected':''}"><td><div class="task-name"><b>${esc(t.title)}</b><span>${esc(t.notes||'No description')}</span></div></td><td>${esc(t.category||'Other')}</td><td><span class="task-pill priority-${esc(t.priority||'normal')}">${esc(priorityLabel(t.priority))}</span></td><td class="task-date ${dateClass(t)}">${isDone(t)?'Completed':esc(fmtDate(t.due_date))}</td><td>${esc(assignment(t))}</td><td><span class="task-pill status-${esc(isDone(t)?'completed':(t.status||'not_started'))}">${esc(statusLabel(isDone(t)?'completed':t.status))}</span></td></tr>`).join('')||'<tr><td colspan="6" class="task-empty">No tasks match this view.</td></tr>';$('taskListCount').textContent=`Showing ${rows.length} of ${tasks.length} tasks`}
  function selected(){return tasks.find(t=>t.id===selectedId)||null}
  function detailTabs(){return `<nav class="task-detail-tabs"><button class="${detailTab==='overview'?'active':''}" data-task-detail-tab="overview">Overview</button><button class="${detailTab==='activity'?'active':''}" data-task-detail-tab="activity">Activity</button><button class="${detailTab==='notes'?'active':''}" data-task-detail-tab="notes">Notes</button></nav>`}
  function upcomingHtml(){const rows=tasks.filter(t=>!isDone(t)&&t.due_date&&t.id!==selectedId).sort((a,b)=>a.due_date.localeCompare(b.due_date)).slice(0,3);return rows.map(t=>`<div class="task-mini-row ${dateClass(t)}"><b>${isOverdue(t)?'Overdue':t.due_date===todayKey()?'Today':t.due_date===addDays(todayKey(),1)?'Tomorrow':fmtDate(t.due_date)}</b><span>${esc(t.title)}</span></div>`).join('')||'<div class="task-description">No other upcoming tasks.</div>'}
  function completedHtml(){return tasks.filter(isDone).sort((a,b)=>new Date(b.completed_at||b.updated_at||0)-new Date(a.completed_at||a.updated_at||0)).slice(0,2).map(t=>`<div class="task-mini-row done"><b>✓</b><span>${esc(t.title)}</span></div>`).join('')||'<div class="task-description">No completed tasks yet.</div>'}
  function renderDetail(){const box=$('taskDetail'),t=selected();if(!box)return;if(!t){box.innerHTML='<div class="task-empty">Select a task to view its details.</div>';return}const top=`<div class="task-detail-top"><h2>${esc(t.title)}</h2><span class="task-pill priority-${esc(t.priority||'normal')}">${esc(priorityLabel(t.priority))}</span></div>${detailTabs()}`;if(detailTab==='activity'){box.innerHTML=top+'<div class="task-detail-body"><section class="task-detail-card"><h3>Task Activity</h3><div id="taskActivityList" class="task-activity"><div class="task-description">Loading activity…</div></div></section></div>';loadActivity(t.id);return}if(detailTab==='notes'){box.innerHTML=top+`<div class="task-detail-body"><section class="task-detail-card task-notes-box"><h3>Internal Notes</h3><textarea id="taskNotesEditor" maxlength="2000" placeholder="Add private notes about this task">${esc(t.admin_notes||'')}</textarea><div class="task-notes-actions"><button class="task-action-btn primary" type="button" data-save-task-notes>Save Notes</button></div><div id="taskNotesStatus" class="task-description"></div></section></div>`;return}box.innerHTML=top+`<div class="task-detail-body"><section class="task-detail-card"><div class="task-detail-head"><h3>Task Details</h3><div class="task-action-row"><button class="task-action-btn" type="button" data-edit-task="${t.id}">✎ Edit</button><button class="task-action-btn primary" type="button" data-toggle-task-complete="${t.id}">${isDone(t)?'↺ Reopen':'✓ Mark Complete'}</button></div></div><div class="task-fields"><div class="task-field"><small>Status</small><b>${esc(statusLabel(isDone(t)?'completed':t.status))}</b></div><div class="task-field"><small>Due Date</small><b>${esc(fmtDate(t.due_date,{month:'long',day:'numeric',year:'numeric'}))}</b></div><div class="task-field"><small>Category</small><b>${esc(t.category||'Other')}</b></div><div class="task-field"><small>Assigned To</small><b>${esc(assignment(t))}</b></div></div></section><section class="task-detail-card"><h3>Description</h3><div class="task-description">${esc(t.notes||'No description added.')}</div></section><section class="task-detail-card"><h3>Upcoming</h3><div class="task-mini-list">${upcomingHtml()}</div></section><section class="task-detail-card"><h3>Recently Completed</h3><div class="task-mini-list">${completedHtml()}</div></section></div>`}
  async function loadActivity(id){const rows=await safe(sb.from('command_todo_activity').select('*').eq('task_id',id).order('created_at',{ascending:false}));if(selectedId!==id||detailTab!=='activity')return;const box=$('taskActivityList');if(!box)return;const labels={created:'Task created',status_changed:'Status changed',assignment_changed:'Assignment changed',due_date_changed:'Due date changed',updated:'Task updated',notes_updated:'Notes updated'};box.innerHTML=rows.map(r=>`<div class="task-activity-row"><span class="task-activity-dot"></span><div><b>${esc(labels[r.action]||'Task updated')}</b><span>${esc(r.detail||'')}${r.actor_id?' · '+esc(personName(r.actor_id)||'Admin'):''}</span></div><time>${esc(fmtTime(r.created_at))}</time></div>`).join('')||'<div class="task-description">No activity recorded yet.</div>'}
  function openModal(id=null){const t=id?tasks.find(x=>x.id===id):null;$('taskFormId').value=t?.id||'';$('taskModalTitle').textContent=t?'Edit Task':'Create Task';$('taskFormTitle').value=t?.title||'';$('taskFormDescription').value=t?.notes||'';$('taskFormCategory').value=t?.category||'Other';$('taskFormPriority').value=t?.priority||'normal';$('taskFormDueDate').value=t?.due_date||'';$('taskFormStatus').value=isDone(t||{})?'completed':(t?.status||'not_started');$('taskFormPerson').value=t?.assigned_to||'';$('taskFormRole').value=t?.assigned_role||'';$('taskFormNotes').value=t?.admin_notes||'';$('taskFormStatusText').textContent='';$('deleteTaskBtn').classList.toggle('hidden',!t);$('taskModal').classList.remove('hidden');setTimeout(()=>$('taskFormTitle')?.focus(),30)}
  function closeModal(){$('taskModal')?.classList.add('hidden')}
  async function saveTask(e){e.preventDefault();if(!currentUser){$('taskFormStatusText').textContent='Your session expired. Refresh and sign in again.';return}const id=$('taskFormId').value,status=$('taskFormStatus').value,payload={title:$('taskFormTitle').value.trim(),notes:$('taskFormDescription').value.trim()||null,category:$('taskFormCategory').value,priority:$('taskFormPriority').value,due_date:$('taskFormDueDate').value||null,status,completed:status==='completed',assigned_to:$('taskFormPerson').value||null,assigned_role:$('taskFormRole').value||null,admin_notes:$('taskFormNotes').value.trim()||null};if(!payload.title){$('taskFormStatusText').textContent='Add a task title.';return}$('taskFormStatusText').textContent='Saving…';let result;if(id)result=await sb.from('command_todos').update(payload).eq('id',id).select('id').single();else result=await sb.from('command_todos').insert({...payload,created_by:currentUser.id}).select('id').single();if(result.error){$('taskFormStatusText').textContent=result.error.message;return}selectedId=result.data?.id||id||selectedId;detailTab='overview';closeModal();await loadTasks()}
  async function deleteTask(){const id=$('taskFormId').value;if(!id||!confirm('Delete this task and its activity history?'))return;const {error}=await sb.from('command_todos').delete().eq('id',id);if(error){$('taskFormStatusText').textContent=error.message;return}selectedId=null;closeModal();await loadTasks()}
  async function toggleComplete(id){const t=tasks.find(x=>x.id===id);if(!t)return;const next=isDone(t)?'in_progress':'completed';const {error}=await sb.from('command_todos').update({status:next,completed:next==='completed'}).eq('id',id);if(error){alert(error.message);return}selectedId=id;detailTab='overview';await loadTasks()}
  async function saveNotes(){const t=selected();if(!t)return;const value=$('taskNotesEditor')?.value.trim()||null;$('taskNotesStatus').textContent='Saving…';const {error}=await sb.from('command_todos').update({admin_notes:value}).eq('id',t.id);if(error){$('taskNotesStatus').textContent=error.message;return}$('taskNotesStatus').textContent='Saved.';await loadTasks();detailTab='notes';renderDetail()}
  function openSiteManagement(){document.querySelectorAll('.admin-nav button').forEach(b=>b.classList.remove('active'));document.querySelector('[data-task-site-management]')?.classList.add('active');if(window.openSiteManagement)window.openSiteManagement();else setTimeout(()=>window.openSiteManagement?.(),150)}

  window.addEventListener('click',e=>{const site=e.target.closest?.('[data-task-site-management]');if(site){e.preventDefault();e.stopImmediatePropagation();openSiteManagement();return}const nav=e.target.closest?.('.admin-nav [data-section]');if(!nav)return;if(nav.dataset.section==='tasks'){e.preventDefault();e.stopImmediatePropagation();showTasks();return}hideTasks()},true);
  document.addEventListener('click',e=>{const row=e.target.closest('[data-task-id]');if(row){selectedId=row.dataset.taskId;detailTab='overview';renderList();renderDetail();return}const lt=e.target.closest('[data-task-list-tab]');if(lt){listTab=lt.dataset.taskListTab;renderList();return}const dt=e.target.closest('[data-task-detail-tab]');if(dt){detailTab=dt.dataset.taskDetailTab;renderDetail();return}if(e.target.closest('#createTaskBtn')){openModal();return}const edit=e.target.closest('[data-edit-task]');if(edit){openModal(edit.dataset.editTask);return}const toggle=e.target.closest('[data-toggle-task-complete]');if(toggle){toggleComplete(toggle.dataset.toggleTaskComplete);return}if(e.target.closest('[data-save-task-notes]')){saveNotes();return}if(e.target.closest('[data-close-task-modal]')){closeModal();return}if(e.target.closest('#deleteTaskBtn')){deleteTask();return}});
  document.addEventListener('submit',e=>{if(e.target.id==='taskForm')saveTask(e)});
  document.addEventListener('input',e=>{if(e.target.id==='taskSearch')renderList()});
  document.addEventListener('change',e=>{if(e.target.id==='taskStatusFilter')renderList()});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('taskModal')?.classList.contains('hidden'))closeModal()});

  ensureUI();loadTasks();setTimeout(loadTasks,900);
  window.openTaskManagement=showTasks;
})();