(()=>{
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let announcements=[],posts=[],photos=[],groups=[],messages=[],events=[],activeTab='announcements',editingAnnouncement=null;
const fmt=d=>d?new Date(d).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'—';
function hideOther(){document.querySelectorAll('.command-head,.stats-grid,.dashboard-grid,.bottom-grid,#cadetWorkspace').forEach(x=>x.classList.add('hidden'));document.getElementById('contentWorkspace')?.classList.remove('hidden');document.querySelectorAll('.admin-nav button').forEach(b=>b.classList.remove('active'));document.querySelector('[data-section="content"]')?.classList.add('active')}
function showContent(){hideOther();loadAll()}
async function safe(p,f=[]){try{const {data,error}=await p;if(error)throw error;return data??f}catch(e){console.warn(e);return f}}
async function loadAll(){const c=window.adminSupabase;if(!c)return;[announcements,posts,photos,groups,messages,events]=await Promise.all([
 safe(c.from('announcements').select('*').order('created_at',{ascending:false})),safe(c.from('message_posts').select('*').order('created_at',{ascending:false})),safe(c.from('gallery_photos').select('*').order('created_at',{ascending:false})),safe(c.from('discussion_groups').select('*').order('created_at',{ascending:false})),safe(c.from('discussion_messages').select('*').order('created_at',{ascending:false})),safe(c.from('events').select('*').order('event_date',{ascending:true}))]);renderAll()}
function renderAll(){
 $('ccAnnouncements').textContent=announcements.length;$('ccMessages').textContent=posts.length;$('ccPhotos').textContent=photos.length;$('ccGroups').textContent=groups.filter(x=>!x.archived).length;
 renderAnnouncements();renderPosts();renderPhotos();renderGroups();renderSide();
}
function renderAnnouncements(){const list=$('announcementList');if(!list)return;list.innerHTML=announcements.map(a=>`<article class="content-row"><div><b>${esc(a.title||'Untitled')}</b><span>${esc(a.category||'General')} · ${fmt(a.created_at)} · ${a.author_name?esc(a.author_name):'Admin'}${a.priority?' · Priority':''}</span></div><div class="content-row-actions"><button data-edit-announcement="${a.id}">Edit</button><button class="danger" data-delete-announcement="${a.id}">Delete</button></div></article>`).join('')||'<p class="content-empty">No announcements yet.</p>'}
function renderPosts(){const list=$('messageModerationList');if(!list)return;list.innerHTML=posts.map(p=>`<article class="content-row"><div><b>${esc(p.title||'Message Board Post')}</b><span>${esc(p.category||'General')} · ${fmt(p.created_at)} · ${p.approved?'Approved':'Pending'}${p.pinned?' · Pinned':''}</span><span>${esc((p.message||'').slice(0,140))}</span></div><div class="content-row-actions">${!p.approved?`<button class="good" data-approve-post="${p.id}">Approve</button>`:''}<button data-pin-post="${p.id}">${p.pinned?'Unpin':'Pin'}</button><button class="danger" data-delete-post="${p.id}">Delete</button></div></article>`).join('')||'<p class="content-empty">No message-board posts.</p>'}
function photoUrl(p){if(!p.storage_path)return'';return window.adminSupabase.storage.from('gallery').getPublicUrl(p.storage_path).data.publicUrl}
function renderPhotos(){const list=$('galleryManageList');if(!list)return;list.innerHTML=photos.map(p=>`<article class="content-row gallery-row"><div class="gallery-row-left"><img class="content-preview" src="${esc(photoUrl(p))}" alt=""><div><b>${esc(p.caption||'Gallery photo')}</b><span>${fmt(p.created_at)} · ${p.approved?'Approved':'Pending'}</span></div></div><div class="content-row-actions">${!p.approved?`<button class="good" data-approve-photo="${p.id}">Approve</button>`:''}<button class="danger" data-delete-photo="${p.id}" data-storage-path="${esc(p.storage_path||'')}">Delete</button></div></article>`).join('')||'<p class="content-empty">No gallery photos.</p>'}
function renderGroups(){const list=$('groupManageList');if(!list)return;list.innerHTML=groups.map(g=>`<article class="content-row"><div><b>${esc(g.name)}</b><span>${esc(g.description||'No description')} · ${g.archived?'Archived':'Active'} · ${messages.filter(m=>m.group_id===g.id).length} messages</span></div><div class="content-row-actions"><button data-archive-group="${g.id}" data-next="${g.archived?'false':'true'}">${g.archived?'Restore':'Archive'}</button><button class="danger" data-delete-group="${g.id}">Delete</button></div></article>`).join('')||'<p class="content-empty">No discussion groups.</p>'}
function renderSide(){
 const upcoming=events.filter(e=>new Date(e.event_date+'T23:59:59')>=new Date()).slice(0,5);$('ccUpcomingEvents').innerHTML=upcoming.map(e=>`<div class="mini-row"><b>${esc(e.title)}</b><span>${fmt(e.event_date+'T00:00:00')}${e.location?' · '+esc(e.location):''}</span></div>`).join('')||'<p class="content-empty">No upcoming events.</p>';
 const activity=[...announcements.slice(0,3).map(x=>({t:x.created_at,b:'Announcement: '+x.title})),...photos.slice(0,2).map(x=>({t:x.created_at,b:'Gallery photo: '+(x.caption||'Uploaded')})),...groups.slice(0,2).map(x=>({t:x.created_at,b:'Group: '+x.name}))].sort((a,b)=>new Date(b.t)-new Date(a.t)).slice(0,5);$('ccRecentActivity').innerHTML=activity.map(x=>`<div class="mini-row"><b>${esc(x.b)}</b><span>${fmt(x.t)}</span></div>`).join('')||'<p class="content-empty">No recent activity.</p>'
}
function switchTab(tab){activeTab=tab;document.querySelectorAll('[data-content-tab]').forEach(b=>b.classList.toggle('active',b.dataset.contentTab===tab));document.querySelectorAll('.content-pane').forEach(p=>p.classList.toggle('active',p.dataset.contentPane===tab))}
async function saveAnnouncement(e){e.preventDefault();const c=window.adminSupabase,{data:{user}}=await c.auth.getUser();const payload={title:$('ccAnnouncementTitle').value.trim(),message:$('ccAnnouncementMessage').value.trim(),category:$('ccAnnouncementCategory').value,priority:$('ccAnnouncementPriority').checked,comments_enabled:$('ccAnnouncementComments').checked,author_id:user.id,author_name:$('adminUserName')?.textContent||'Admin'};$('ccAnnouncementStatus').textContent='Saving…';let q=editingAnnouncement?c.from('announcements').update(payload).eq('id',editingAnnouncement):c.from('announcements').insert(payload);const {error}=await q;if(error){$('ccAnnouncementStatus').textContent=error.message;return}editingAnnouncement=null;e.target.reset();$('ccAnnouncementComments').checked=true;$('ccAnnouncementFormTitle').textContent='Create & Publish Announcement';$('ccAnnouncementStatus').textContent='Published.';await loadAll()}
function editAnnouncement(id){const a=announcements.find(x=>String(x.id)===String(id));if(!a)return;editingAnnouncement=a.id;$('ccAnnouncementTitle').value=a.title||'';$('ccAnnouncementMessage').value=a.message||'';$('ccAnnouncementCategory').value=a.category||'General';$('ccAnnouncementPriority').checked=!!a.priority;$('ccAnnouncementComments').checked=a.comments_enabled!==false;$('ccAnnouncementFormTitle').textContent='Edit Announcement';switchTab('announcements');$('ccAnnouncementTitle').focus()}
async function del(table,id){const {error}=await window.adminSupabase.from(table).delete().eq('id',id);if(error)alert(error.message);else await loadAll()}
async function patch(table,id,payload){const {error}=await window.adminSupabase.from(table).update(payload).eq('id',id);if(error)alert(error.message);else await loadAll()}
async function saveGroup(e){e.preventDefault();const c=window.adminSupabase,{data:{user}}=await c.auth.getUser();const {error}=await c.from('discussion_groups').insert({name:$('ccGroupName').value.trim(),description:$('ccGroupDescription').value.trim()||null,created_by:user.id,archived:false});if(error){$('ccGroupStatus').textContent=error.message;return}e.target.reset();$('ccGroupStatus').textContent='Group created.';await loadAll()}
async function uploadPhoto(e){e.preventDefault();const c=window.adminSupabase,file=$('ccGalleryFile').files[0];if(!file)return;const {data:{user}}=await c.auth.getUser(),path=`${user.id}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;$('ccGalleryStatus').textContent='Uploading…';let r=await c.storage.from('gallery').upload(path,file,{upsert:false});if(r.error){$('ccGalleryStatus').textContent=r.error.message;return}r=await c.from('gallery_photos').insert({uploader_id:user.id,storage_path:path,caption:$('ccGalleryCaption').value.trim()||null,approved:true});if(r.error){$('ccGalleryStatus').textContent=r.error.message;return}e.target.reset();$('ccGalleryStatus').textContent='Uploaded.';await loadAll()}
async function saveEvent(e){e.preventDefault();const c=window.adminSupabase,{data:{user}}=await c.auth.getUser();const payload={title:$('ccEventTitle').value.trim(),event_type:$('ccEventType').value,description:$('ccEventDescription').value.trim()||null,event_date:$('ccEventDate').value,start_time:$('ccEventStart').value||null,end_time:$('ccEventEnd').value||null,location:$('ccEventLocation').value.trim()||null,author_id:user.id};const {error}=await c.from('events').insert(payload);if(error){$('ccEventStatus').textContent=error.message;return}$('ccEventStatus').textContent='Event added.';e.target.reset();setTimeout(()=>document.getElementById('ccEventModal').classList.add('hidden'),350);await loadAll()}
document.addEventListener('click',e=>{
 const contentNav=e.target.closest('[data-section="content"]');if(contentNav){e.preventDefault();e.stopImmediatePropagation();showContent();return}
 const tab=e.target.closest('[data-content-tab]');if(tab){switchTab(tab.dataset.contentTab);return}
 if(e.target.closest('[data-open-announcement]')){showContent();switchTab('announcements');$('ccAnnouncementTitle')?.focus();return}
 if(e.target.closest('[data-open-event]')){$('ccEventModal').classList.remove('hidden');return}
 if(e.target.closest('[data-close-event]')){$('ccEventModal').classList.add('hidden');return}
 const ea=e.target.closest('[data-edit-announcement]');if(ea){editAnnouncement(ea.dataset.editAnnouncement);return}
 const da=e.target.closest('[data-delete-announcement]');if(da&&confirm('Delete this announcement?'))del('announcements',da.dataset.deleteAnnouncement);
 const ap=e.target.closest('[data-approve-post]');if(ap)patch('message_posts',ap.dataset.approvePost,{approved:true});
 const pp=e.target.closest('[data-pin-post]');if(pp){const p=posts.find(x=>String(x.id)===String(pp.dataset.pinPost));if(p)patch('message_posts',p.id,{pinned:!p.pinned})}
 const dp=e.target.closest('[data-delete-post]');if(dp&&confirm('Delete this message-board post?'))del('message_posts',dp.dataset.deletePost);
 const ph=e.target.closest('[data-approve-photo]');if(ph)patch('gallery_photos',ph.dataset.approvePhoto,{approved:true});
 const dph=e.target.closest('[data-delete-photo]');if(dph&&confirm('Delete this gallery photo?')){const path=dph.dataset.storagePath;if(path)window.adminSupabase.storage.from('gallery').remove([path]);del('gallery_photos',dph.dataset.deletePhoto)}
 const ag=e.target.closest('[data-archive-group]');if(ag)patch('discussion_groups',ag.dataset.archiveGroup,{archived:ag.dataset.next==='true'});
 const dg=e.target.closest('[data-delete-group]');if(dg&&confirm('Delete this discussion group?'))del('discussion_groups',dg.dataset.deleteGroup);
},true);
document.addEventListener('submit',e=>{if(e.target.id==='ccAnnouncementForm')saveAnnouncement(e);else if(e.target.id==='ccGroupForm')saveGroup(e);else if(e.target.id==='ccGalleryForm')uploadPhoto(e);else if(e.target.id==='ccEventForm')saveEvent(e)});
window.openContentCommunication=showContent;
})();