(()=>{
const sb=window.adminSupabase;if(!sb)return;const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));const slots=[['service_coat','Service Coat'],['lightweight_jacket','Lightweight Jacket'],['ocp','OCPs'],['pt_gear','PT Gear']];let rows={};const pub=p=>sb.storage.from('uniform-guide').getPublicUrl(p).data.publicUrl;
function loadTaskWorkspace(){if(window.__afjrotcTaskWorkspace||document.querySelector('script[data-admin-tasks]'))return;const s=document.createElement('script');s.src='/admin-tasks.js?v=1';s.async=false;s.dataset.adminTasks='1';document.body.appendChild(s)}
function rewriteCompactBlock(){const panels=[...document.querySelectorAll('.bottom-grid .panel')];const panel=panels.find(p=>p.querySelector('h2')?.textContent.trim()==='Site Management');if(!panel)return;const grid=panel.querySelector('.quick-grid');if(!grid)return;grid.innerHTML='<button type="button" data-uniform-photo-tool>Uniform Guide Photos</button><button type="button" data-edit-handbook>Edit Cadet Handbook</button><button type="button" data-manage-alerts>Site Alerts</button><button type="button" data-section="cadets">Access & Roles</button>'}
function mountUniformModal(){if($('uniformPhotoToolModal'))return;document.body.insertAdjacentHTML('beforeend',`<div id="uniformPhotoToolModal" class="content-modal hidden"><div class="content-modal-card" style="width:min(94vw,980px);max-width:980px;max-height:88vh;overflow:auto"><div class="content-modal-head"><h2>Uniform Guide Photos</h2><button type="button" data-close-uniform-photo-tool>×</button></div><p class="muted">Upload, replace, or remove the real photos shown in the Uniform Guide.</p><div id="compactUniformGrid" class="site-uniform-grid"></div></div></div>`)}
async function loadUniform(){mountUniformModal();const {data,error}=await sb.from('uniform_guide_images').select('*');if(error)return;rows={};(data||[]).forEach(r=>rows[r.slot]=r);renderUniform()}
function renderUniform(){const box=$('compactUniformGrid');if(!box)return;box.innerHTML=slots.map(([k,n])=>{const r=rows[k];return `<article class="content-card"><h3>${n}</h3><div style="min-height:180px;display:grid;place-items:center;border:1px solid var(--line);border-radius:12px;overflow:hidden;margin:10px 0">${r?`<img src="${esc(pub(r.storage_path))}" alt="${esc(r.alt_text||n)}" style="max-width:100%;max-height:240px;object-fit:contain">`:'No photo uploaded'}</div><label>Photo<input id="cupFile-${k}" type="file" accept="image/png,image/jpeg,image/webp"></label><label>Alt text<input id="cupAlt-${k}" value="${esc(r?.alt_text||n+' uniform reference photo')}"></label><div class="content-row-actions"><button class="primary" type="button" data-cup-upload="${k}">${r?'Replace':'Upload'}</button>${r?`<button class="danger" type="button" data-cup-remove="${k}">Remove</button>`:''}</div><div id="cupStatus-${k}" class="content-status"></div></article>`}).join('')}
async function upload(k){const f=$(`cupFile-${k}`)?.files?.[0],st=$(`cupStatus-${k}`);if(!f){st.textContent='Choose a photo first.';return}if(f.size>8*1024*1024){st.textContent='Photo must be under 8 MB.';return}st.textContent='Uploading…';const path=`${k}/${Date.now()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await sb.storage.from('uniform-guide').upload(path,f);if(up.error){st.textContent=up.error.message;return}const old=rows[k]?.storage_path,{data:{user}}=await sb.auth.getUser();const q=await sb.from('uniform_guide_images').upsert({slot:k,storage_path:path,alt_text:$(`cupAlt-${k}`).value.trim(),updated_at:new Date().toISOString(),updated_by:user.id},{onConflict:'slot'});if(q.error){st.textContent=q.error.message;return}if(old)await sb.storage.from('uniform-guide').remove([old]);await loadUniform()}
async function remove(k){if(!confirm('Remove this Uniform Guide photo?'))return;const r=rows[k];if(!r)return;await sb.storage.from('uniform-guide').remove([r.storage_path]);await sb.from('uniform_guide_images').delete().eq('slot',k);await loadUniform()}
function loadExtraTools(){if(document.querySelector('script[data-handbook-alert-tools]'))return;const s=document.createElement('script');s.src='/admin-handbook-alerts.js?v=109';s.dataset.handbookAlertTools='1';document.body.appendChild(s)}
document.addEventListener('click',e=>{if(e.target.closest('[data-uniform-photo-tool]')){mountUniformModal();$('uniformPhotoToolModal').classList.remove('hidden');loadUniform()}if(e.target.closest('[data-close-uniform-photo-tool]'))$('uniformPhotoToolModal')?.classList.add('hidden');const u=e.target.closest('[data-cup-upload]');if(u)upload(u.dataset.cupUpload);const r=e.target.closest('[data-cup-remove]');if(r)remove(r.dataset.cupRemove)});
function init(){document.getElementById('siteWorkspace')?.remove();rewriteCompactBlock();mountUniformModal();loadExtraTools();loadTaskWorkspace()}
init();setTimeout(init,300);setTimeout(init,1200);window.openSiteManagement=()=>{mountUniformModal();$('uniformPhotoToolModal').classList.remove('hidden');loadUniform()};
})();