(()=>{
const RANKS=[
  ["C/AB","Cadet Airman Basic"],["C/Amn","Cadet Airman"],["C/A1C","Cadet Airman First Class"],["C/SrA","Cadet Senior Airman"],
  ["C/SSgt","Cadet Staff Sergeant"],["C/TSgt","Cadet Technical Sergeant"],["C/MSgt","Cadet Master Sergeant"],["C/SMSgt","Cadet Senior Master Sergeant"],["C/CMSgt","Cadet Chief Master Sergeant"],
  ["C/2d Lt","Cadet Second Lieutenant"],["C/1st Lt","Cadet First Lieutenant"],["C/Capt","Cadet Captain"],["C/Maj","Cadet Major"],["C/Lt Col","Cadet Lieutenant Colonel"],["C/Col","Cadet Colonel"]
];
const isAdmin=()=>!!currentProfile&&["command_staff","instructor"].includes(currentProfile.role);
const isLeader=()=>currentProfile?.role==="class_leader";
let rankRoster=[],flightAnnouncements=[],siteSettings=null,adminTodos=[],adminCadets=[];

function styles(){if(document.getElementById("cadetSystemStyles"))return;const s=document.createElement("style");s.id="cadetSystemStyles";s.textContent=`
.flight-hero,.settings-hero,.rank-hero{background:linear-gradient(135deg,#0b1b31,#1d4f91);color:#fff;border-radius:20px;padding:24px;margin-bottom:16px}.flight-hero h1,.settings-hero h1,.rank-hero h1{margin:3px 0 5px}.flight-meta{display:flex;gap:9px;flex-wrap:wrap;margin-top:12px}.flight-chip{background:#ffffff18;border:1px solid #ffffff32;border-radius:999px;padding:6px 10px;font-size:.8rem}.flight-grid,.settings-grid,.rank-grid,.assignment-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.rank-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.feature-card{background:#fff;border:1px solid #dde4ec;border-radius:16px;padding:17px}.feature-card h3{margin:0 0 8px}.roster-row,.flight-announcement,.todo-row,.assignment-row{padding:11px 0;border-bottom:1px solid #e8edf2}.roster-row:last-child,.flight-announcement:last-child,.todo-row:last-child,.assignment-row:last-child{border-bottom:0}.roster-row b,.assignment-row b{display:block}.roster-row small,.assignment-row small,.todo-row small{color:#64748b}.flight-announcement p,.todo-row p{margin:6px 0;color:#526071}.settings-section label{display:flex;align-items:flex-start;gap:10px;font-size:.9rem;margin:9px 0}.settings-section input[type=checkbox]{width:auto;margin:2px 0}.settings-section select{margin-top:5px}.rank-card{background:#fff;border:1px solid #dde4ec;border-radius:16px;padding:16px}.rank-card h3{margin:0}.rank-card .rank-code{font-size:1.2rem;font-weight:900;color:#1d4f91}.rank-holders{margin-top:10px;padding-top:10px;border-top:1px solid #edf1f5}.rank-holder{font-size:.82rem;padding:4px 0;color:#44566a}.todo-toolbar{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:12px}.todo-toolbar button{border:1px solid #d7e0e9;background:#fff;border-radius:9px;padding:7px 10px}.todo-priority{font-size:.72rem;font-weight:900;text-transform:uppercase;border-radius:999px;padding:4px 7px;background:#eef2ff}.todo-priority.high,.todo-priority.urgent{background:#fff1f1;color:#9b2f2f}.assignment-row{display:grid;grid-template-columns:minmax(150px,1.2fr) repeat(3,minmax(120px,1fr)) auto;gap:10px;align-items:end}.assignment-row label{margin:0}.assignment-row input,.assignment-row select{margin-top:4px}.admin-todo-form{display:grid;grid-template-columns:2fr 1fr 1fr 1fr;gap:10px;align-items:end}.admin-todo-form .todo-notes{grid-column:1/-1}.settings-status{font-size:.85rem;color:#17683a;margin-top:9px}.home-compact .public-panel,.home-compact .public-stat-card{padding:12px!important}.home-compact .public-grid2{gap:10px!important}.larger-site-text{font-size:112%}.force-reduced-motion *{animation:none!important;transition:none!important;scroll-behavior:auto!important}
@media(max-width:800px){.flight-grid,.settings-grid,.rank-grid,.assignment-grid{grid-template-columns:1fr}.admin-todo-form{grid-template-columns:1fr}.assignment-row{grid-template-columns:1fr}.flight-hero,.settings-hero,.rank-hero{padding:19px}}
`;document.head.appendChild(s)}

function addNavButton(nav,label,page,id){if(!nav||document.getElementById(id))return;const b=document.createElement("button");b.id=id;b.dataset.public=page;b.className="hidden";b.textContent=label;nav.appendChild(b)}
function injectPublic(){
  const site=document.getElementById("publicSite");if(!site||document.getElementById("public-flight"))return;
  addNavButton(document.querySelector(".public-nav"),"My Flight","flight","flightNavBtn");
  addNavButton(document.querySelector(".public-nav"),"Ranks & Info","ranks","ranksNavBtn");
  addNavButton(document.querySelector(".public-nav"),"Settings","site-settings","settingsNavBtn");
  addNavButton(document.getElementById("mobileNav"),"My Flight","flight","mobileFlightNavBtn");
  addNavButton(document.getElementById("mobileNav"),"Ranks & Info","ranks","mobileRanksNavBtn");
  addNavButton(document.getElementById("mobileNav"),"Settings","site-settings","mobileSettingsNavBtn");
  site.insertAdjacentHTML("beforeend",`
  <section id="public-flight" class="public-page"><div class="flight-hero"><p class="eyebrow light">MY FLIGHT</p><h1 id="flightPageTitle">Flight</h1><p id="flightPageSubtitle">Your assigned AFJROTC flight.</p><div id="flightMeta" class="flight-meta"></div></div><div class="flight-grid"><article class="feature-card"><h3>Flight Roster</h3><div id="flightRoster"></div></article><article class="feature-card"><h3>Flight Announcements</h3><div id="flightAnnouncementForm"></div><div id="flightAnnouncements"></div></article></div></section>
  <section id="public-ranks" class="public-page"><div class="rank-hero"><p class="eyebrow light">CADET INFORMATION</p><h1>Ranks & AFJROTC Information</h1><p>Review the cadet rank structure and see the ranks currently represented in the unit.</p></div><div id="rankInfoGrid" class="rank-grid"></div></section>
  <section id="public-site-settings" class="public-page"><div class="settings-hero"><p class="eyebrow light">MY ACCOUNT</p><h1>Settings</h1><p>Control your homepage, accessibility, notifications, and privacy preferences.</p></div><form id="siteSettingsForm"><div class="settings-grid"><article class="feature-card settings-section"><h3>Homepage</h3><label><input id="setCompactHome" type="checkbox">Compact homepage layout</label><label><input id="setHomeUniform" type="checkbox">Show uniform on homepage</label><label><input id="setHomeEvents" type="checkbox">Show events on homepage</label><label><input id="setHomeAnnouncements" type="checkbox">Show announcements on homepage</label><label><input id="setHomeService" type="checkbox">Show service shortcut on homepage</label><label><input id="setHomeGroups" type="checkbox">Show groups shortcut on homepage</label></article><article class="feature-card settings-section"><h3>Notifications</h3><label><input id="setNotifyAnnouncements" type="checkbox">Announcement updates</label><label><input id="setNotifyComments" type="checkbox">Comments and replies</label><label><input id="setNotifyGroups" type="checkbox">Group activity</label><label><input id="setNotifyEvents" type="checkbox">Event changes</label></article><article class="feature-card settings-section"><h3>Accessibility</h3><label><input id="setLargerText" type="checkbox">Use larger website text</label><label><input id="setReducedMotion" type="checkbox">Reduce animations and motion</label></article><article class="feature-card settings-section"><h3>Privacy</h3><label>Profile visibility<select id="setProfileVisibility"><option value="unit">Visible to signed-in unit members</option><option value="private">Private except administrators</option></select></label><p class="muted">Your flight and rank may still appear where needed for unit organization.</p></article></div><button class="primary" style="margin-top:14px">Save Settings</button><p id="siteSettingsStatus" class="settings-status"></p></form></section>`);
}

function syncPublicAccess(){const signed=!!sessionUser;["flightNavBtn","ranksNavBtn","settingsNavBtn","mobileFlightNavBtn","mobileRanksNavBtn","mobileSettingsNavBtn"].forEach(id=>document.getElementById(id)?.classList.toggle("hidden",!signed));if(document.getElementById("profileFlight")){document.getElementById("profileFlight").disabled=true;document.getElementById("profileFlight").placeholder="Assigned by admin"}if(document.getElementById("profilePosition")){document.getElementById("profilePosition").disabled=true;document.getElementById("profilePosition").placeholder="Assigned by admin"}}

async function loadRoster(){if(!sessionUser){rankRoster=[];return}const {data,error}=await sb.rpc("list_rank_roster");if(!error)rankRoster=data||[];renderRanks();renderFlight()}
async function loadFlightAnnouncements(){if(!sessionUser||!currentProfile?.flight){flightAnnouncements=[];renderFlight();return}const {data,error}=await sb.from("flight_announcements").select("*").eq("flight",currentProfile.flight).order("created_at",{ascending:false});if(!error)flightAnnouncements=data||[];renderFlight()}
function nameFor(id){return rankRoster.find(p=>p.id===id)?.full_name||"Unit Member"}
function renderFlight(){
  const title=document.getElementById("flightPageTitle");if(!title)return;const flight=currentProfile?.flight;
  if(!flight){title.textContent="No Flight Assigned";document.getElementById("flightPageSubtitle").textContent="An administrator has not assigned your account to a flight yet.";document.getElementById("flightMeta").innerHTML="";document.getElementById("flightRoster").innerHTML="<p class='muted'>No roster available.</p>";document.getElementById("flightAnnouncements").innerHTML="<p class='muted'>No flight announcements available.</p>";document.getElementById("flightAnnouncementForm").innerHTML="";return}
  const members=rankRoster.filter(p=>p.flight===flight);const leader=members.find(p=>p.role==="class_leader");title.textContent=`${flight} Flight`;document.getElementById("flightPageSubtitle").textContent="Your flight roster, leadership, and announcements.";document.getElementById("flightMeta").innerHTML=`<span class="flight-chip">${members.length} member${members.length===1?"":"s"}</span><span class="flight-chip">Class Leader: ${esc(leader?.full_name||"Not assigned")}</span>`;
  document.getElementById("flightRoster").innerHTML=members.map(p=>`<div class="roster-row"><b>${esc(p.full_name||"Cadet")}</b><small>${esc(p.cadet_rank||"Rank not assigned")}${p.cadet_position?` • ${esc(p.cadet_position)}`:""}${p.role==="class_leader"?" • Class Leader":""}</small></div>`).join("")||"<p class='muted'>No cadets assigned.</p>";
  const canPost=(isLeader()&&currentProfile.flight===flight)||isAdmin();document.getElementById("flightAnnouncementForm").innerHTML=canPost?`<form id="newFlightAnnouncementForm" style="margin-bottom:14px"><label>Title<input id="flightAnnouncementTitle" maxlength="120" required></label><label>Announcement<textarea id="flightAnnouncementMessage" maxlength="1200" required></textarea></label><button class="primary">Post to ${esc(flight)} Flight</button></form>`:"";
  const form=document.getElementById("newFlightAnnouncementForm");if(form)form.onsubmit=async e=>{e.preventDefault();const {error}=await sb.from("flight_announcements").insert({flight,title:document.getElementById("flightAnnouncementTitle").value.trim(),message:document.getElementById("flightAnnouncementMessage").value.trim(),author_id:sessionUser.id});if(error)return alert(error.message);e.target.reset();await loadFlightAnnouncements()};
  document.getElementById("flightAnnouncements").innerHTML=flightAnnouncements.map(a=>`<div class="flight-announcement"><b>${esc(a.title)}</b><small class="post-author">Posted by ${esc(nameFor(a.author_id))} • ${new Date(a.created_at).toLocaleDateString()}</small><p>${esc(a.message)}</p>${(isAdmin()||(isLeader()&&a.author_id===sessionUser.id))?`<button class="text-btn danger-link" data-delete-flight-announcement="${a.id}">Delete</button>`:""}</div>`).join("")||"<p class='muted'>No flight announcements yet.</p>";
}
function renderRanks(){const grid=document.getElementById("rankInfoGrid");if(!grid)return;grid.innerHTML=RANKS.map(([code,name])=>{const holders=rankRoster.filter(p=>p.cadet_rank===code);return `<article class="rank-card"><div class="rank-code">${esc(code)}</div><h3>${esc(name)}</h3><div class="rank-holders"><b>Cadets with this rank</b>${holders.length?holders.map(p=>`<div class="rank-holder">${esc(p.full_name)}${p.flight?` • ${esc(p.flight)} Flight`:""}</div>`).join(""):"<p class='muted'>None assigned right now.</p>"}</div></article>`}).join("")}

async function loadSettings(){if(!sessionUser){siteSettings=null;return}let {data}=await sb.from("user_site_settings").select("*").eq("user_id",sessionUser.id).maybeSingle();if(!data){const created=await sb.from("user_site_settings").insert({user_id:sessionUser.id}).select().single();data=created.data}siteSettings=data||null;renderSettings();applySettings()}
function renderSettings(){if(!siteSettings)return;const map={setCompactHome:"compact_home",setHomeUniform:"show_home_uniform",setHomeEvents:"show_home_events",setHomeAnnouncements:"show_home_announcements",setHomeService:"show_home_service",setHomeGroups:"show_home_groups",setNotifyAnnouncements:"notifications_announcements",setNotifyComments:"notifications_comments",setNotifyGroups:"notifications_groups",setNotifyEvents:"notifications_events",setLargerText:"larger_text",setReducedMotion:"reduced_motion"};Object.entries(map).forEach(([id,key])=>{const el=document.getElementById(id);if(el)el.checked=!!siteSettings[key]});if(document.getElementById("setProfileVisibility"))document.getElementById("setProfileVisibility").value=siteSettings.profile_visibility||"unit"}
function applySettings(){document.documentElement.classList.toggle("larger-site-text",!!siteSettings?.larger_text);document.documentElement.classList.toggle("force-reduced-motion",!!siteSettings?.reduced_motion);const home=document.getElementById("public-home");home?.classList.toggle("home-compact",!!siteSettings?.compact_home);if(!home)return;const panels=[...home.querySelectorAll(".public-panel")];const stat=[...home.querySelectorAll(".public-stat-card")];const show=(el,val)=>{if(el)el.style.display=val?"":"none"};show(panels.find(x=>x.textContent.includes("UNIFORM OF THE WEEK")),siteSettings?.show_home_uniform!==false);show(panels.find(x=>x.textContent.includes("UPCOMING EVENTS")),siteSettings?.show_home_events!==false);show(panels.find(x=>x.textContent.includes("LATEST ANNOUNCEMENTS")),siteSettings?.show_home_announcements!==false);show(stat.find(x=>x.textContent.includes("Uniform")),siteSettings?.show_home_uniform!==false);show(stat.find(x=>x.textContent.includes("Upcoming Events")),siteSettings?.show_home_events!==false)}
function bindSettings(){const form=document.getElementById("siteSettingsForm");if(!form||form.dataset.bound)return;form.dataset.bound="1";form.onsubmit=async e=>{e.preventDefault();const payload={user_id:sessionUser.id,compact_home:document.getElementById("setCompactHome").checked,show_home_uniform:document.getElementById("setHomeUniform").checked,show_home_events:document.getElementById("setHomeEvents").checked,show_home_announcements:document.getElementById("setHomeAnnouncements").checked,show_home_service:document.getElementById("setHomeService").checked,show_home_groups:document.getElementById("setHomeGroups").checked,notifications_announcements:document.getElementById("setNotifyAnnouncements").checked,notifications_comments:document.getElementById("setNotifyComments").checked,notifications_groups:document.getElementById("setNotifyGroups").checked,notifications_events:document.getElementById("setNotifyEvents").checked,larger_text:document.getElementById("setLargerText").checked,reduced_motion:document.getElementById("setReducedMotion").checked,profile_visibility:document.getElementById("setProfileVisibility").value,updated_at:new Date().toISOString()};const {data,error}=await sb.from("user_site_settings").upsert(payload).select().single();if(error)return alert(error.message);siteSettings=data;applySettings();document.getElementById("siteSettingsStatus").textContent="Settings saved."}}

function injectAdmin(){const nav=document.getElementById("adminNav"),main=document.querySelector(".admin-main");if(!nav||!main||document.getElementById("admin-assignments"))return;const before=nav.querySelector('[data-admin="settings"]');const a=document.createElement("button");a.dataset.admin="assignments";a.textContent="Cadet Assignments";nav.insertBefore(a,before);const t=document.createElement("button");t.dataset.admin="todos";t.textContent="Command To-Do";nav.insertBefore(t,before);main.insertAdjacentHTML("beforeend",`<section id="admin-assignments" class="admin-page"><div class="page-head"><h1>Cadet Assignments</h1><p>Assign flights, ranks, and positions. Cadets cannot change these themselves.</p></div><article class="panel"><div id="adminAssignmentList"></div></article></section><section id="admin-todos" class="admin-page"><div class="page-head"><h1>Command Staff To-Do</h1><p>Keep command tasks, due dates, priorities, and assignments in one place.</p></div><div class="grid2"><article class="panel"><h3>Add Task</h3><form id="commandTodoForm" class="admin-todo-form"><label>Task<input id="todoTitle" required maxlength="180"></label><label>Due date<input id="todoDue" type="date"></label><label>Priority<select id="todoPriority"><option value="normal">Normal</option><option value="low">Low</option><option value="high">High</option><option value="urgent">Urgent</option></select></label><label>Assign to<select id="todoAssignee"><option value="">Unassigned</option></select></label><label class="todo-notes">Notes<textarea id="todoNotes" maxlength="1200"></textarea></label><button class="primary">Add Task</button></form></article><article class="panel"><div class="todo-toolbar"><button data-todo-filter="open">Open</button><button data-todo-filter="mine">My Tasks</button><button data-todo-filter="all">All</button><button data-todo-filter="completed">Completed</button></div><div id="commandTodoList"></div></article></div></section>`)}
async function loadAdminTools(){if(!isAdmin())return;const [{data:cadets},{data:todos},{data:staff}]=await Promise.all([sb.rpc("list_rank_roster"),sb.from("command_todos").select("*").order("completed").order("due_date",{ascending:true,nullsFirst:false}),sb.from("profiles").select("id,full_name,role").in("role",["command_staff","instructor"]).order("full_name")]);adminCadets=cadets||[];adminTodos=todos||[];const ass=document.getElementById("todoAssignee");if(ass)ass.innerHTML='<option value="">Unassigned</option>'+((staff||[]).filter(p=>p.role==="command_staff").map(p=>`<option value="${p.id}">${esc(p.full_name||"Command Staff")}</option>`).join(""));renderAssignments();renderTodos("open");bindTodoForm()}
function renderAssignments(){const el=document.getElementById("adminAssignmentList");if(!el)return;el.innerHTML=adminCadets.filter(p=>p.role!=="instructor").map(p=>`<div class="assignment-row" data-cadet="${p.id}"><div><b>${esc(p.full_name||"Cadet")}</b><small>${esc(roleLabel?.(p.role)||p.role)}</small></div><label>Flight<input data-field="flight" value="${esc(p.flight||"")}" placeholder="Alpha"></label><label>Rank<select data-field="rank"><option value="">Not assigned</option>${RANKS.map(([c,n])=>`<option value="${esc(c)}" ${p.cadet_rank===c?"selected":""}>${esc(c)} — ${esc(n)}</option>`).join("")}</select></label><label>Position<input data-field="position" value="${esc(p.cadet_position||"")}" placeholder="Optional"></label><button class="primary" data-save-assignment="${p.id}">Save</button></div>`).join("")||"<p class='muted'>No cadets found.</p>"}
function renderTodos(filter="open"){const el=document.getElementById("commandTodoList");if(!el)return;let rows=adminTodos;if(filter==="open")rows=rows.filter(t=>!t.completed);if(filter==="completed")rows=rows.filter(t=>t.completed);if(filter==="mine")rows=rows.filter(t=>!t.completed&&t.assigned_to===sessionUser.id);el.innerHTML=rows.map(t=>`<div class="todo-row"><div><span class="todo-priority ${esc(t.priority)}">${esc(t.priority)}</span> <b>${esc(t.title)}</b></div><small>${t.due_date?`Due ${new Date(t.due_date+"T12:00:00").toLocaleDateString()}`:"No due date"}${t.assigned_to?` • Assigned to ${esc((adminCadets.find(p=>p.id===t.assigned_to)?.full_name)||"Command Staff")}`:" • Unassigned"}</small><p>${esc(t.notes||"")}</p><button class="text-btn" data-toggle-todo="${t.id}" data-completed="${t.completed}">${t.completed?"Reopen":"Mark complete"}</button> <button class="text-btn danger-link" data-delete-todo="${t.id}">Delete</button></div>`).join("")||"<p class='muted'>No tasks in this view.</p>"}
function bindTodoForm(){const f=document.getElementById("commandTodoForm");if(!f||f.dataset.bound)return;f.dataset.bound="1";f.onsubmit=async e=>{e.preventDefault();const {error}=await sb.from("command_todos").insert({title:document.getElementById("todoTitle").value.trim(),notes:document.getElementById("todoNotes").value.trim()||null,due_date:document.getElementById("todoDue").value||null,priority:document.getElementById("todoPriority").value,assigned_to:document.getElementById("todoAssignee").value||null,created_by:sessionUser.id});if(error)return alert(error.message);e.target.reset();await loadAdminTools()}}

document.addEventListener("click",async e=>{const del=e.target.closest("[data-delete-flight-announcement]");if(del){const {error}=await sb.from("flight_announcements").delete().eq("id",del.dataset.deleteFlightAnnouncement);if(error)return alert(error.message);await loadFlightAnnouncements();return}const save=e.target.closest("[data-save-assignment]");if(save){const row=save.closest(".assignment-row"),id=save.dataset.saveAssignment;const get=f=>row.querySelector(`[data-field="${f}"]`).value;const {error}=await sb.rpc("admin_update_cadet_details",{target_user_id:id,new_flight:get("flight")||null,new_rank:get("rank")||null,new_position:get("position")||null});if(error)return alert(error.message);save.textContent="Saved";setTimeout(()=>save.textContent="Save",1000);await loadAdminTools();return}const tog=e.target.closest("[data-toggle-todo]");if(tog){const completed=tog.dataset.completed==="true";const {error}=await sb.from("command_todos").update({completed:!completed,completed_at:completed?null:new Date().toISOString()}).eq("id",tog.dataset.toggleTodo);if(error)return alert(error.message);await loadAdminTools();return}const td=e.target.closest("[data-delete-todo]");if(td){const {error}=await sb.from("command_todos").delete().eq("id",td.dataset.deleteTodo);if(error)return alert(error.message);await loadAdminTools();return}const filter=e.target.closest("[data-todo-filter]");if(filter){renderTodos(filter.dataset.todoFilter)}});

const oldRenderAuth=renderAuth;renderAuth=function(){oldRenderAuth();syncPublicAccess();if(sessionUser){loadRoster();loadFlightAnnouncements();loadSettings();bindSettings()}else{siteSettings=null;applySettings()}};
const oldRenderAdmin=renderAdmin;renderAdmin=function(){oldRenderAdmin();injectAdmin();loadAdminTools()};
styles();injectPublic();injectAdmin();syncPublicAccess();bindSettings();if(sessionUser){loadRoster();loadFlightAnnouncements();loadSettings()}if(isAdmin())loadAdminTools();
})();