(()=>{
const RANKS=[
  ["C/AB","Cadet Airman Basic"],["C/Amn","Cadet Airman"],["C/A1C","Cadet Airman First Class"],["C/SrA","Cadet Senior Airman"],
  ["C/SSgt","Cadet Staff Sergeant"],["C/TSgt","Cadet Technical Sergeant"],["C/MSgt","Cadet Master Sergeant"],["C/SMSgt","Cadet Senior Master Sergeant"],["C/CMSgt","Cadet Chief Master Sergeant"],
  ["C/2d Lt","Cadet Second Lieutenant"],["C/1st Lt","Cadet First Lieutenant"],["C/Capt","Cadet Captain"],["C/Maj","Cadet Major"],["C/Lt Col","Cadet Lieutenant Colonel"],["C/Col","Cadet Colonel"]
];
const isAdmin=()=>!!currentProfile&&["command_staff","instructor"].includes(currentProfile.role);
const isLeader=()=>currentProfile?.role==="class_leader";
let rankRoster=[],flightAnnouncements=[],siteSettings=null,adminTodos=[],adminCadets=[];

function styles(){if(document.getElementById("cadetSystemStyles"))return;const s=document.createElement("style");s.id="cadetSystemStyles";s.textContent=`
.flight-hero,.settings-hero,.rank-hero{background:linear-gradient(135deg,#0b1b31,#1d4f91);color:#fff;border-radius:20px;padding:24px;margin-bottom:16px}.flight-hero h1,.settings-hero h1,.rank-hero h1{margin:3px 0 5px}.flight-meta{display:flex;gap:9px;flex-wrap:wrap;margin-top:12px}.flight-chip{background:#ffffff18;border:1px solid #ffffff32;border-radius:999px;padding:6px 10px;font-size:.8rem}.flight-grid,.settings-grid,.rank-grid,.assignment-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.rank-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.feature-card{background:#fff;border:1px solid #dde4ec;border-radius:16px;padding:17px}.feature-card h3{margin:0 0 8px}.roster-row,.flight-announcement,.todo-row,.assignment-row{padding:11px 0;border-bottom:1px solid #e8edf2}.roster-row:last-child,.flight-announcement:last-child,.todo-row:last-child,.assignment-row:last-child{border-bottom:0}.roster-row b,.assignment-row b{display:block}.roster-row small,.assignment-row small,.todo-row small{color:#64748b}.flight-announcement p,.todo-row p{margin:6px 0;color:#526071}.settings-section label{display:flex;align-items:flex-start;gap:10px;font-size:.9rem;margin:9px 0}.settings-section input[type=checkbox]{width:auto;margin:2px 0}.settings-section select{margin-top:5px}.rank-card{background:#fff;border:1px solid #dde4ec;border-radius:16px;padding:16px}.rank-card h3{margin:0}.rank-card .rank-code{font-size:1.2rem;font-weight:900;color:#1d4f91}.rank-holders{margin-top:10px;padding-top:10px;border-top:1px solid #edf1f5}.rank-holder{font-size:.82rem;padding:4px 0;color:#44566a}.home-compact .public-panel,.home-compact .public-stat-card{padding:12px!important}.home-compact .public-grid2{gap:10px!important}.larger-site-text{font-size:112%}.force-reduced-motion *{animation:none!important;transition:none!important;scroll-behavior:auto!important}@media(max-width:800px){.flight-grid,.settings-grid,.rank-grid{grid-template-columns:1fr}.flight-hero,.settings-hero,.rank-hero{padding:19px}}
`;document.head.appendChild(s)}
function addNavButton(nav,label,page,id){if(!nav||document.getElementById(id))return;const b=document.createElement("button");b.id=id;b.dataset.public=page;b.className="hidden";b.textContent=label;nav.appendChild(b)}
function injectPublic(){const site=document.getElementById("publicSite");if(!site||document.getElementById("public-flight"))return;addNavButton(document.querySelector(".public-nav"),"My Flight","flight","flightNavBtn");addNavButton(document.querySelector(".public-nav"),"Ranks & Info","ranks","ranksNavBtn");addNavButton(document.querySelector(".public-nav"),"Settings","site-settings","settingsNavBtn");addNavButton(document.getElementById("mobileNav"),"My Flight","flight","mobileFlightNavBtn");addNavButton(document.getElementById("mobileNav"),"Ranks & Info","ranks","mobileRanksNavBtn");addNavButton(document.getElementById("mobileNav"),"Settings","site-settings","mobileSettingsNavBtn");site.insertAdjacentHTML("beforeend",`
<section id="public-flight" class="public-page"><div class="flight-hero"><p class="eyebrow light">MY FLIGHT</p><h1 id="flightPageTitle">Flight</h1><p id="flightPageSubtitle">Your assigned AFJROTC flight.</p><div id="flightMeta" class="flight-meta"></div></div><div class="flight-grid"><article class="feature-card"><h3>Flight Roster</h3><div id="flightRoster"></div></article><article class="feature-card"><h3>Flight Announcements</h3><div id="flightAnnouncementForm"></div><div id="flightAnnouncements"></div></article></div></section>
<section id="public-ranks" class="public-page"><div id="rankInfoGrid"></div></section>
<section id="public-site-settings" class="public-page"><div class="settings-hero"><p class="eyebrow light">MY ACCOUNT</p><h1>Settings</h1><p>Control your homepage, accessibility, notifications, and privacy preferences.</p></div><form id="siteSettingsForm"><div class="settings-grid"><article class="feature-card settings-section"><h3>Homepage</h3><label><input id="setCompactHome" type="checkbox">Compact homepage layout</label><label><input id="setHomeUniform" type="checkbox">Show uniform on homepage</label><label><input id="setHomeEvents" type="checkbox">Show events on homepage</label><label><input id="setHomeAnnouncements" type="checkbox">Show announcements on homepage</label><label><input id="setHomeService" type="checkbox">Show service shortcut on homepage</label><label><input id="setHomeGroups" type="checkbox">Show groups shortcut on homepage</label></article><article class="feature-card settings-section"><h3>Notifications</h3><label><input id="setNotifyAnnouncements" type="checkbox">Announcement updates</label><label><input id="setNotifyComments" type="checkbox">Comments and replies</label><label><input id="setNotifyGroups" type="checkbox">Group activity</label><label><input id="setNotifyEvents" type="checkbox">Event changes</label></article><article class="feature-card settings-section"><h3>Accessibility</h3><label><input id="setLargerText" type="checkbox">Use larger website text</label><label><input id="setReducedMotion" type="checkbox">Reduce animations and motion</label></article><article class="feature-card settings-section"><h3>Privacy</h3><label>Profile visibility<select id="setProfileVisibility"><option value="unit">Visible to signed-in unit members</option><option value="private">Private except administrators</option></select></label><p class="muted">Your flight and rank may still appear where needed for unit organization.</p></article></div><button class="primary" style="margin-top:14px">Save Settings</button><p id="siteSettingsStatus" class="settings-status"></p></form></section>`)}
function syncPublicAccess(){const signed=!!sessionUser;["flightNavBtn","ranksNavBtn","settingsNavBtn","mobileFlightNavBtn","mobileRanksNavBtn","mobileSettingsNavBtn"].forEach(id=>document.getElementById(id)?.classList.toggle("hidden",!signed))}
async function loadRoster(){if(!sessionUser){rankRoster=[];return}const {data,error}=await sb.rpc("list_rank_roster");if(!error)rankRoster=data||[];renderFlight()}
async function loadFlightAnnouncements(){if(!sessionUser||!currentProfile?.flight){flightAnnouncements=[];renderFlight();return}const {data,error}=await sb.from("flight_announcements").select("*").eq("flight",currentProfile.flight).order("created_at",{ascending:false});if(!error)flightAnnouncements=data||[];renderFlight()}
function nameFor(id){return rankRoster.find(p=>p.id===id)?.full_name||"Unit Member"}
function renderFlight(){const title=document.getElementById("flightPageTitle");if(!title)return;const flight=currentProfile?.flight;if(!flight){title.textContent="No Flight Assigned";document.getElementById("flightPageSubtitle").textContent="An administrator has not assigned your account to a flight yet.";document.getElementById("flightMeta").innerHTML="";document.getElementById("flightRoster").innerHTML="<p class='muted'>No roster available.</p>";document.getElementById("flightAnnouncements").innerHTML="<p class='muted'>No flight announcements available.</p>";document.getElementById("flightAnnouncementForm").innerHTML="";return}const members=rankRoster.filter(p=>p.flight===flight);const leader=members.find(p=>p.role==="class_leader");title.textContent=`${flight} Flight`;document.getElementById("flightPageSubtitle").textContent="Your flight roster, leadership, and announcements.";document.getElementById("flightMeta").innerHTML=`<span class="flight-chip">${members.length} member${members.length===1?"":"s"}</span><span class="flight-chip">Class Leader: ${esc(leader?.full_name||"Not assigned")}</span>`;document.getElementById("flightRoster").innerHTML=members.map(p=>`<div class="roster-row"><b>${esc(p.full_name||"Cadet")}</b><small>${esc(p.cadet_rank||"Rank not assigned")}</small></div>`).join("")||"<p class='muted'>No cadets assigned.</p>";document.getElementById("flightAnnouncements").innerHTML=flightAnnouncements.map(a=>`<div class="flight-announcement"><b>${esc(a.title)}</b><small>${esc(nameFor(a.author_id))}</small><p>${esc(a.message)}</p></div>`).join("")||"<p class='muted'>No flight announcements yet.</p>"}
async function loadSettings(){if(!sessionUser){siteSettings=null;return}const {data}=await sb.from("user_site_settings").select("*").eq("user_id",sessionUser.id).maybeSingle();siteSettings=data||null;renderSettings();applySettings()}
function renderSettings(){if(!siteSettings)return;const map={setCompactHome:"compact_home",setHomeUniform:"show_home_uniform",setHomeEvents:"show_home_events",setHomeAnnouncements:"show_home_announcements",setHomeService:"show_home_service",setHomeGroups:"show_home_groups",setNotifyAnnouncements:"notifications_announcements",setNotifyComments:"notifications_comments",setNotifyGroups:"notifications_groups",setNotifyEvents:"notifications_events",setLargerText:"larger_text",setReducedMotion:"reduced_motion"};Object.entries(map).forEach(([id,key])=>{const el=document.getElementById(id);if(el)el.checked=!!siteSettings[key]})}
function applySettings(){document.documentElement.classList.toggle("larger-site-text",!!siteSettings?.larger_text);document.documentElement.classList.toggle("force-reduced-motion",!!siteSettings?.reduced_motion)}
function bindSettings(){}
function injectAdmin(){}
function loadAdminTools(){}
const oldRenderAuth=renderAuth;renderAuth=function(){oldRenderAuth();syncPublicAccess();if(sessionUser){loadRoster();loadFlightAnnouncements();loadSettings()}else{siteSettings=null;applySettings()}};
styles();injectPublic();syncPublicAccess();if(sessionUser){loadRoster();loadFlightAnnouncements();loadSettings()}
})();