(()=>{
  const LOCAL_VERSION="2026.08.20.60";
  const UPDATED_AT="2026-08-20T23:40:00Z";
  const SHORT_VERSION="v60";
  const fmt=date=>new Date(date).toLocaleString("en-US",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit"});
  function injectStyles(){if(document.getElementById("siteVersionStyles"))return;const style=document.createElement("style");style.id="siteVersionStyles";style.textContent=`#siteVersionWrap{position:fixed;right:16px;bottom:16px;z-index:99999;font-family:inherit}#siteVersionBadge{border:1px solid #cbd5e1;background:#fff;color:#0f172a;border-radius:999px;padding:9px 12px;display:flex;align-items:center;gap:8px;box-shadow:0 10px 30px rgba(15,23,42,.14);font-size:12px;font-weight:700;cursor:pointer}#siteVersionDot{width:9px;height:9px;border-radius:50%;background:#16a34a;box-shadow:0 0 0 3px rgba(22,163,74,.12)}#siteVersionWrap.update-available #siteVersionDot{background:#d97706;box-shadow:0 0 0 3px rgba(217,119,6,.12)}#siteVersionPanel{position:absolute;right:0;bottom:48px;width:min(320px,calc(100vw - 32px));background:#fff;border:1px solid #e2e8f0;border-radius:16px;padding:16px;box-shadow:0 18px 50px rgba(15,23,42,.16)}#siteVersionPanel.hidden{display:none}#siteVersionPanel h3{margin:0 0 8px;font-size:16px}#siteVersionPanel p{margin:6px 0;color:#475569;font-size:13px;line-height:1.45}#siteVersionPanel button{margin-top:10px;width:100%;border:0;border-radius:10px;padding:10px 12px;background:#0f172a;color:#fff;font-weight:700;cursor:pointer}#siteVersionPanel small{display:block;margin-top:9px;color:#64748b}@media(max-width:640px){#siteVersionWrap{right:10px;bottom:10px}#siteVersionBadge{padding:8px 10px}}`;document.head.appendChild(style)}
  function mount(){if(document.getElementById("siteVersionWrap"))return;injectStyles();const wrap=document.createElement("div");wrap.id="siteVersionWrap";wrap.innerHTML=`<button id="siteVersionBadge" type="button" aria-expanded="false"><span id="siteVersionDot"></span><span id="siteVersionBadgeText">Site up to date · ${SHORT_VERSION}</span></button><div id="siteVersionPanel" class="hidden"><h3>Site status</h3><p id="siteVersionStatusText">You are viewing the newest known AFJROTC build.</p><p><b>Version:</b> ${LOCAL_VERSION}<br><b>Last updated:</b> ${fmt(UPDATED_AT)}</p><button id="siteVersionCheck" type="button">Check for updates</button><small id="siteVersionCheckResult">The site checks the live version file, not your browser cache.</small></div>`;document.body.appendChild(wrap);const badge=document.getElementById("siteVersionBadge"),panel=document.getElementById("siteVersionPanel");badge.addEventListener("click",()=>{const hidden=panel.classList.toggle("hidden");badge.setAttribute("aria-expanded",String(!hidden))});document.getElementById("siteVersionCheck").addEventListener("click",checkForUpdates)}
  async function checkForUpdates(){const result=document.getElementById("siteVersionCheckResult"),text=document.getElementById("siteVersionStatusText"),badgeText=document.getElementById("siteVersionBadgeText"),wrap=document.getElementById("siteVersionWrap");if(result)result.textContent="Checking live site version…";try{const manifest=await fetch(`/version.json?t=${Date.now()}`,{cache:"no-store"}).then(r=>{if(!r.ok)throw new Error("Version check failed");return r.json()});if(manifest.version!==LOCAL_VERSION){wrap?.classList.add("update-available");if(text)text.textContent="A newer site build is available.";if(badgeText)badgeText.textContent="New version available";if(result)result.innerHTML=`Latest: ${manifest.version}. <button id="siteVersionReload" type="button" style="margin-top:8px">Load newest version</button>`;document.getElementById("siteVersionReload")?.addEventListener("click",()=>window.location.reload())}else{wrap?.classList.remove("update-available");if(text)text.textContent="You are viewing the newest AFJROTC build.";if(badgeText)badgeText.textContent=`Site up to date · ${SHORT_VERSION}`;if(result)result.textContent=`Checked just now · ${fmt(new Date())}`}}catch(err){if(result)result.textContent="Could not verify the live version. Try again in a moment.";console.error("Version check error",err)}}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",mount,{once:true});else mount();
})();